server:
  port: 9990
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: viewservice
          uri: lb://viewservice
          predicates:
            - Path=/api/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: BONREE